#!/bin/bash

set -e

LXCCMD=${LXCCMD:-lxc}
ACCNT=$(id -u -n)
LXCIMAGE=${LXCIMAGE:-lxd-terminal-$ACCNT}
LXCEXEC="${LXCCMD} exec ${LXCIMAGE} --"

# Ensure it is running
${LXCCMD} start ${LXCIMAGE} 2> /dev/null || true

# Stop when done
cleanup () {
	${LXCCMD} stop ${LXCIMAGE} || true
}
trap cleanup EXIT

${SNAP}/usr/libexec/gnome-terminal-server
