#!/bin/bash

set -e

LXCCMD=${LXCCMD:-lxc}
ACCNT=$(id -u -n)
LXCIMAGE=${LXCIMAGE:-lxd-terminal-$ACCNT}
LXCEXEC="${LXCCMD} exec ${LXCIMAGE} --"

zenity --window-icon ${SNAP}/share/lxd-terminal-delete.svg --question --default-cancel --title="LXD Terminal Delete" --text="Deleting the container for LXD Terminal will remove all installed packages and cause a new container to be built the next time you run the program.\n\nDo you want to delete the container?" && ( ${LXCCMD} delete -f ${LXCIMAGE} | zenity --window-icon ${SNAP}/share/lxd-terminal-delete.svg --progress --pulsate --no-cancel --title="LXD Terminal Delete" --text="Deleting LXD Terminal Container: ${LXCIMAGE}" )
