#!/bin/bash

set -e

LXCCMD=${LXCCMD:-lxc}
ACCNT=$USERNAME
LXCIMAGE=${LXCIMAGE:-lxd-terminal-$ACCNT}
LXCEXEC="${LXCCMD} exec ${LXCIMAGE} --"

# Ensure we have one
${SNAP}/lxd-terminal-create

exec ${LXCEXEC} login -f ${ACCNT}
