#!/bin/bash

set -e

LXCCMD=${LXCCMD:-lxc}
ACCNT=$USERNAME
LXCIMAGE=${LXCIMAGE:-lxd-terminal-$ACCNT}
LXCEXEC="${LXCCMD} exec ${LXCIMAGE} --"

# Ensure we have one
${SNAP}/lxd-terminal-create

# Ensure it is running
${LXCCMD} start ${LXCIMAGE} 2> /dev/null || true

# Stop when done
cleanup () {
	${LXCCMD} stop ${LXCIMAGE}
}
trap cleanup EXIT

${SNAP}/usr/libexec/gnome-terminal-server
