name: lxd-terminal
base: core22
version: '0.3'
summary: Terminal Application that uses an LXD Container
description: |
  Fully confined Developer Console which uses an
  on-the-fly created LXD container to execute in. Allows for a flexible
  writable environment without requiring unconfined applications.
  .
  Technically speaking this is mostly GNOME Terminal with a bunch of
  wrapper scripts and small diffs to make it work in that fashion.
  .
  You'll need to execute a couple of commands to make this work
  ```
  snap set system experimental.user-daemons=true
  ```

grade: stable
confinement: strict

parts:
  gnome-terminal:
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/gnome-terminal.git
    source-tag: gnome-42 # matches core22
    override-pull: |
      snapcraftctl pull
      # Make it so we don't conflict
      sed -i "s|/org/gnome/Terminal|/cx/gould/LXDTerminal|" $SNAPCRAFT_PART_SRC/src/terminal-defines.hh
      sed -i "s|org.gnome.Terminal|cx.gould.lxdterminal|" $SNAPCRAFT_PART_SRC/src/terminal-defines.hh
      sed -i "s|GNOME_TERMINAL_SERVICE|LXD_TERMINAL_SERVICE|" $SNAPCRAFT_PART_SRC/src/terminal-defines.hh
      sed -i "s|GNOME_TERMINAL_SCREEN|LXD_TERMINAL_SCREEN|" $SNAPCRAFT_PART_SRC/src/terminal-defines.hh
      sed -i "s|org.gnome.Terminal|cx.gould.lxdterminal|" $SNAPCRAFT_PART_SRC/src/org.gnome.Terminal.xml
      sed -i "s|gdk_set_program_class(\"Gnome-terminal\");|gdk_set_program_class(\"lxd-terminal\");|" $SNAPCRAFT_PART_SRC/src/terminal-app.cc
      sed -i "s|g_set_prgname(\"gnome-terminal-server\");|g_set_prgname(\"lxd-terminal-server\");|" $SNAPCRAFT_PART_SRC/src/server.cc
      # Change the default shell
      cp $SNAPCRAFT_PROJECT_DIR/eggshell.cc $SNAPCRAFT_PART_SRC/src/
    build-packages:
      - desktop-file-utils
      - docbook-to-man
      - docbook-xsl
      - gettext
      - gsettings-desktop-schemas-dev
      - itstool
      - libdconf-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libpcre2-dev
      - libvte-2.91-dev
      - uuid-dev
      - xsltproc 
    meson-parameters:
      - -Ddocs=false
      - -Dnautilus_extension=false
      - -Dsearch_provider=false
      - -Dprefix=/usr
    stage-packages:
      - adwaita-icon-theme-full
      - dmz-cursor-theme
      - fonts-noto
      - fonts-ubuntu
      - fonts-ubuntu-console
      - gsettings-desktop-schemas
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libdconf1
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf-2.0-0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libicu70
      - libjpeg-turbo8
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - librsvg2-common
      - libthai0
      - libvte-2.91-0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - locales
      - locales-all
      - libc-bin
      - yaru-theme-gtk
    override-prime: |
      snapcraftctl prime
      glib-compile-schemas $SNAPCRAFT_PRIME/usr/share/glib-2.0/schemas
      GDK_PIXBUF_MODULEDIR=$SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/gdk-pixbuf-loaders.cache
      sed -i "s|$SNAPCRAFT_PRIME||" $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/gdk-pixbuf-loaders.cache
      $SNAPCRAFT_PRIME/usr/bin/update-mime-database $SNAPCRAFT_PRIME/usr/share/mime/
  lxd-terminal-scripts:
    plugin: dump
    source: .
    source-subdir: scripts
  lxd-terminal-data:
    plugin: dump
    source: .
    source-subdir: data
  lxd-client:
    plugin: go
    source: https://github.com/lxc/lxd.git
    source-tag: stable-5.0
    override-build: |
      go install ./lxc
  gtk-locales:
    plugin: nil
    override-pull: |
      set -eux
      apt-get download "language-pack-gnome-*-base"
    override-build: |
      set -eux
      for deb in *.deb; do dpkg-deb -x $deb .; done
      find usr/share/locale-langpack -type f -not -name "gtk30*.mo" -and -not -name "glib*.mo" -and -not -name "gdk*.mo" -and -not -name "libsoup*.mo" -and -not -name "gspell*.mo" -delete
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
      cp -r usr/share/locale-langpack $SNAPCRAFT_PART_INSTALL/usr/share/
  zenity: # Build instead of the Ubuntu package because it pulls in webkit, which is 100MB larger
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/zenity.git
    source-tag: 3.42.1
    build-packages:
      - libgtk-3-dev
    meson-parameters:
      - -Dprefix=/usr
    stage:
      - -usr/share/help

slots:
  lxd-terminal-dbus-slot:
    interface: dbus
    bus: session
    name: cx.gould.lxdterminal
plugs:
  lxd-terminal-dbus-plug:
    interface: dbus
    bus: session
    name: cx.gould.lxdterminal

apps:
  lxd-terminal:
    command: lxd-terminal-launch
    desktop: share/cx.gould.lxdterminal.desktop
    environment:
      GDK_PIXBUF_MODULE_FILE: /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/gdk-pixbuf-loaders.cache
      LXCCMD: $SNAP/bin/lxc
      LXD_DIR: /var/snap/lxd/common/lxd
      XDG_DATA_DIRS: $XDG_DATA_DIRS:$SNAP/usr/share
    plugs:
      - lxd-terminal-dbus-plug
      - lxd
      - desktop
      - x11
      - wayland
  delete:
    command: lxd-terminal-delete
    desktop: share/lxd-terminal-delete.desktop
    environment:
      GDK_PIXBUF_MODULE_FILE: /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/gdk-pixbuf-loaders.cache
      LXCCMD: $SNAP/bin/lxc
      LXD_DIR: /var/snap/lxd/common/lxd
      XDG_DATA_DIRS: $XDG_DATA_DIRS:$SNAP/usr/share
    plugs:
      - lxd-terminal-dbus-plug
      - lxd
      - desktop
      - x11
      - wayland
  server:
    command: lxd-terminal-server
    daemon: simple
    passthrough:
      daemon-scope: user
      activates-on:
        - lxd-terminal-dbus-slot
    environment:
      GDK_PIXBUF_MODULE_FILE: /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/gdk-pixbuf-loaders.cache
      LXCCMD: $SNAP/bin/lxc
      LXD_DIR: /var/snap/lxd/common/lxd
      XDG_DATA_DIRS: $XDG_DATA_DIRS:$SNAP/usr/share
    slots:
      - lxd-terminal-dbus-slot
    plugs:
      - lxd
      - desktop
      - gsettings
      - x11
      - wayland

layout:
  /usr/share:
    bind: $SNAP/usr/share
  /usr/lib/locale:
    bind: $SNAP/usr/lib/locale
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gnome-terminal:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gnome-terminal
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0

