name: lxd-terminal
base: core22
version: '0.1alpha'
summary: Terminal Application that uses an LXD Container
description: |
  Fully confined Terminal Application that for the console uses an
  on-the-fly created LXD container to execute in. Allows for a flexible
  writable environment without requiring unconfined applications.
  .
  Technically speaking this is mostly GNOME Terminal with a bunch of
  wrapper scripts and small diffs to make it work in that fashion.

grade: stable
confinement: strict

parts:
  gnome-terminal:
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/gnome-terminal.git
    source-tag: gnome-42 # matches core22
    override-pull: |
      snapcraftctl pull
      # Make it so we don't conflict on dbus
      sed -i "s|org.gnome.Terminal|cx.gould.lxd-terminal|" $SNAPCRAFT_PART_SRC/src/terminal-defines.hh
    build-packages:
      - desktop-file-utils
      - docbook-to-man
      - docbook-xsl
      - gettext
      - gsettings-desktop-schemas-dev
      - itstool
      - libdconf-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libpcre2-dev
      - libvte-2.91-dev
      - uuid-dev
      - xsltproc 
    meson-parameters:
      - -Ddocs=false
      - -Dnautilus_extension=false
      - -Dsearch_provider=false
      - -Dprefix=/usr
    stage-packages:
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libdconf1
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf-2.0-0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libicu70
      - libjpeg-turbo8
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libvte-2.91-0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
    override-prime: |
      snapcraftctl prime
      glib-compile-schemas $SNAPCRAFT_PRIME/usr/share/glib-2.0/schemas
  lxd-terminal-scripts:
    plugin: dump
    source: .
    source-subdir: scripts
  lxd-client:
    plugin: go
    source: .
    override-pull: |
      GO111MODULE=off go get -v -x github.com/lxc/lxd/lxc
    override-build: |
      GO111MODULE=off go install github.com/lxc/lxd/lxc

slots:
  lxd-terminal-dbus:
    interface: dbus
    bus: session
    name: cx.gould.lxd-terminal

apps:
  lxd-terminal:
    command: usr/bin/gnome-terminal -- $SNAP/lxd-terminal-run
    environment:
      LXCCMD: $SNAP/bin/lxc
      LXD_DIR: /var/snap/lxd/common/lxd
      XDG_DATA_DIRS: $XDG_DATA_DIRS:$SNAP/usr/share
    slots:
      - lxd-terminal-dbus
    plugs:
      - lxd
      - desktop
      - gsettings
      - x11
      - wayland
